---
title: "Triangulizador"
author: "Galileo Cappella"
date: "September 27, 2018"
output: html_document
---

```{r}
MI <- matrix( #Matriz de identidad
  c(1, 0, 0, 0,
    0, 1, 0, 0,
    0, 0, 1, 0,
    0, 0, 0, 1),
  nrow = 4,
  ncol = 4,
  byrow = TRUE
)

MTestGen <- matrix( #Una para testear en general
  c(3, 9, 3, 12,
    5, 1, 4, 6,
    0, 3, 5, 10,
    8, 0, 1, 1),
  nrow = 4,
  ncol = 4,
  byrow = TRUE
)
```

```{r}
#TODOS LOS PRINT ESTAN PARA DEBUGEAR

triangular <- function(mat) {
    print("Matriz inicial")
    print(mat)

  for(i in 1:NROW(mat)){
    print("i Nro")
    print(i)
    
    Order <- order(mat[i:NROW(mat),i], decreasing = TRUE) #Averigua el orden (decreciente) para la columna qe esta. Esto me asegura qe no haya un cero en el pivote (lo normalizo despues de ordenarlas).
    
    print("Order")
    print(Order)

    mat[i:NROW(mat),i:NCOL(mat)] <- mat[Order,i:NCOL(mat)] #Reorganiza las filas en base a las columnas qe todavia no triangul'o.
    #PROBLEMA: De la segunda pasada en adelante, cuando le doy el orden le estoy diciendo (en base a los valores para el orden qe qeda despues de la primera pasada usando MTestGen): "A la [2,] reemplazala con [2,], a la [3,] con [3,] y a la [4,] con [1,]". PORQE ESE ES EL ORDEN DE LAS TRES FILAS QE LE PEDI QE ORGANIZE, TENDRIA QE QEDAR: "A la [2,] reemplazala con [3,], a la [3,] con [4,] y a la [4,] con [2,]". Para entender mejor, revisar: "Fin de este paso" (i = 1);  "Order" (i = 2); "Matrix" (i = 2).
    
    print("Matrix:")
    print(mat)
    print("DIM")
    print(dim(mat))
    
    mat[i,] <- mat[i,] / mat[i,i] #Normalizo el pivote
    print("Normalizada:")
    print(mat)
    
    for(t in 2:NROW(mat)) { #Qiero qe reste a las filas de la columna para volver cero a esta columna (excepto por el pivote).
        print("t")
        print(t)
        print("tAnt")
        print(mat[t,])
        
        mat[t,] <- mat[t,] - mat[t,i] #A toda la fila le resta el primer valor
        
        print("tNew")
        print(mat[t,])
    }
    print("Fin de este paso")
    print(mat)
  }

 print("Done")
 return(mat)
}

triangular(MTestGen)
```
```{r}
#Tendra futuro para arreglar el problema del orden?
test <- c(5, 4, 2, 3) #Le pongo valores cualqiera

print(test)
print(test[2:4])
print(order(test))
print(order(test[2:4]))
```

